// Mocks generated by Mockito 5.4.5 from annotations
// in poke_api/test/src/controllers/homeController/home_controller.test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_api/src/models/pokemon_detail_model.dart' as _i5;
import 'package:poke_api/src/models/pokemon_model.dart' as _i4;
import 'package:poke_api/src/models/pokemon_move_details.dart' as _i6;
import 'package:poke_api/src/services/poke_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PokeApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokeApi extends _i1.Mock implements _i2.PokeApi {
  MockPokeApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Pokemon?> getPokemon({required dynamic pokemonId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemon, [], {#pokemonId: pokemonId}),
            returnValue: _i3.Future<_i4.Pokemon?>.value(),
          )
          as _i3.Future<_i4.Pokemon?>);

  @override
  _i3.Future<_i5.PkmDetails?> getPokemonDetails({required dynamic pkmName}) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonDetails, [], {#pkmName: pkmName}),
            returnValue: _i3.Future<_i5.PkmDetails?>.value(),
          )
          as _i3.Future<_i5.PkmDetails?>);

  @override
  _i3.Future<_i6.PkmMoveDetails?> getMoveDetails({required dynamic url}) =>
      (super.noSuchMethod(
            Invocation.method(#getMoveDetails, [], {#url: url}),
            returnValue: _i3.Future<_i6.PkmMoveDetails?>.value(),
          )
          as _i3.Future<_i6.PkmMoveDetails?>);
}
